version: '3.8'

services:
  api:
    build: .
    container_name: express_practice_api
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=production
    restart: always
